### ISSUE TITLE
con.csv causing windows error

### ISSUE THREAD

**Issue by rob-bits** [git-plm/parts#19]
The con filename is somehow not valid on my Windows 10 system. I cannot clone the library, exctract the downloaded zip repo, because it drops a windows error on the con.csv file.

When I would like to create a file anywhere on my disk as con.csv or con.txt I got the following error:
The specified device name is invalid.

See this:
https://superuser.com/questions/86999/why-cant-i-name-a-folder-or-file-con-in-windows

Suggestion:
use different file name

**Comment by cbrake** [comment]
we renamed all the `xxx.csv` files to `g-xxx.csv` -- hopefully that fixes this problem.

https://github.com/git-plm/parts/pull/31
