### ISSUE TITLE
envsetup.sh is for linux

### ISSUE THREAD

**Issue by the-last-code-bender** [git-plm/parts#28]

**Comment by cbrake** [comment]
yes `envsetup.sh` is for Linux as that is what I use. Do you need something for Windows, or why did you open this issue?

**Comment by the-last-code-bender** [comment]
[c_u_stetup.txt](https://github.com/user-attachments/files/17262748/c_u_stetup.txt)
Change .txt extension as bat and con.csv should renamed as conn.csv

**Comment by cbrake** [comment]
Thanks, that looks good!

all the category codes are three letters, so we use `con` instead of `conn`.

Can you open up a pull request with this change and perhaps add some documentation to README for windows?
